[package]
authors = ["Wilson Lin <npm@wilsonl.in>", "Aron Homberg <info@aron-homberg.de>"]
description = "Extremely fast JS minifier"
edition = "2021"
name = "better-minify-js-cli"
publish = false
version = "0.7.0"

[dependencies]
better-minify-js = { path = "../rust" }
structopt = "0.3"
